# Generated by Django 5.0.1 on 2024-03-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScanForm', '0002_nomineeinfo_permanentaddress_personalinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('citizenship_no', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('issued_district', models.CharField(max_length=255)),
                ('issued_date', models.DateField()),
                ('first_name_nominee', models.CharField(max_length=255)),
                ('middle_name_nominee', models.CharField(max_length=255)),
                ('last_name_nominee', models.CharField(max_length=255)),
                ('citizenship_no_nominee', models.CharField(max_length=255)),
                ('temp_district', models.CharField(max_length=255)),
                ('temp_house_no', models.CharField(max_length=255)),
                ('temp_vdc', models.CharField(max_length=255)),
                ('temp_ward_no', models.CharField(max_length=255)),
                ('perm_user_id', models.CharField(max_length=255)),
                ('perm_district', models.CharField(max_length=255)),
                ('perm_house_no', models.CharField(max_length=255)),
                ('perm_vdc', models.CharField(max_length=255)),
                ('perm_ward_no', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='NomineeInfo',
        ),
        migrations.DeleteModel(
            name='PermanentAddress',
        ),
        migrations.DeleteModel(
            name='PersonalInfo',
        ),
        migrations.DeleteModel(
            name='TemporaryAddress',
        ),
    ]
