# Generated by Django 5.0.1 on 2024-03-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScanForm', '0003_clientdetails_delete_nomineeinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='issued_date',
            field=models.CharField(max_length=255),
        ),
    ]
