# Generated by Django 5.0.1 on 2024-03-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScanForm', '0004_alter_clientdetails_issued_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='form_name',
            field=models.CharField(default=1234567, max_length=255),
            preserve_default=False,
        ),
    ]
