# Generated by Django 5.0.1 on 2024-04-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScanForm', '0005_clientdetails_form_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='uploaded_date',
            field=models.DateField(null=True),
        ),
    ]
