# Generated by Django 5.0.1 on 2024-04-15 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScanForm', '0006_clientdetails_uploaded_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='uploaded_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 15, 11, 9, 7, 177914, tzinfo=datetime.timezone.utc)),
        ),
    ]
