# Generated by Django 5.0.1 on 2024-04-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScanForm', '0007_alter_clientdetails_uploaded_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='uploaded_date',
            field=models.DateTimeField(null=True),
        ),
    ]
