# Generated by Django 5.0.1 on 2024-04-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScanForm', '0008_alter_clientdetails_uploaded_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
