# Generated by Django 5.0.1 on 2024-04-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScanForm', '0009_clientdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='phone_number',
            field=models.CharField(default='123456789', max_length=255),
        ),
    ]
