# Generated by Django 5.0.1 on 2024-04-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScanForm', '0010_clientdetails_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetails',
            name='citizenship_no',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='citizenship_no_nominee',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='first_name_nominee',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='form_name',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='issued_date',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='issued_district',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='last_name_nominee',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='middle_name_nominee',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='perm_district',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='perm_house_no',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='perm_user_id',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='perm_vdc',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='perm_ward_no',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='status',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='temp_district',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='temp_house_no',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='temp_vdc',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='temp_ward_no',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='uploaded_date',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='user_id',
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='citizenship_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='course',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='date_of_birth',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='guardian_first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='guardian_last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='guardian_middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='guardian_phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='higher_secondary_cgpa',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='higher_secondary_district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='higher_secondary_school_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='higher_secondary_year_completion',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='permanent_district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='permanent_municipality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='permanent_province',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='permanent_ward_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='permanent_zip_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='relation_to_student',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='secondary_cgpa',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='secondary_district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='secondary_school_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='secondary_year_completion',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='temporary_district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='temporary_municipality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='temporary_province',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='temporary_ward_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='temporary_zip_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
