# Generated by Django 5.0.1 on 2024-04-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScanForm', '0012_remove_clientdetails_citizenship_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='citizenship_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='course',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='date_of_birth',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='guardian_first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='guardian_last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='guardian_middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='guardian_phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='higher_secondary_cgpa',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='higher_secondary_district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='higher_secondary_school_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='higher_secondary_year_completion',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='permanent_district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='permanent_municipality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='permanent_province',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='permanent_ward_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='permanent_zip_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='relation_to_student',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='secondary_cgpa',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='secondary_district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='secondary_school_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='secondary_year_completion',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='temporary_district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='temporary_municipality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='temporary_province',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='temporary_ward_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='temporary_zip_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
