# Generated by Django 5.0.1 on 2024-04-29 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScanForm', '0013_clientdetails_citizenship_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='form_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='uploaded_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='uploaded_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
