# Generated by Django 5.0.1 on 2024-04-29 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScanForm', '0014_clientdetails_form_name_clientdetails_uploaded_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetails',
            name='uploaded_by',
        ),
    ]
