# Generated by Django 5.0.1 on 2024-04-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScanForm', '0015_remove_clientdetails_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='higher_secondary_cgpa',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='secondary_cgpa',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
